// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEntry(arg1) {
  return window['go']['backend']['App']['DeleteEntry'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['backend']['App']['GetConnectionStatus']();
}

export function GetDevices() {
  return window['go']['backend']['App']['GetDevices']();
}

export function GetEntries() {
  return window['go']['backend']['App']['GetEntries']();
}

export function GetIsLoggedIn() {
  return window['go']['backend']['App']['GetIsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['backend']['App']['Login'](arg1, arg2);
}
