// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetIsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<models.Error>;
