// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {backend} from '../models';

export function ConnectToWS():Promise<models.Error>;

export function DeleteEntry(arg1:string):Promise<models.Error>;

export function GetConnectionStatus():Promise<boolean>;

export function GetDeviceId():Promise<number>;

export function GetDevices():Promise<Array<models.Device>|models.Error>;

export function GetEntries():Promise<backend.GetEntriesResponse>;

export function GetIsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<models.Error>;
