// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type ClipboardEntry struct {
	EntryID       uuid.UUID `json:"entry_id"`
	FromDeviceID  int32     `json:"from_device_id"`
	ToDeviceID    int32     `json:"to_device_id"`
	EncryptedData string    `json:"encrypted_data"`
	CreatedAt     time.Time `json:"created_at"`
}

type Device struct {
	DeviceID   int32     `json:"device_id"`
	UserID     int32     `json:"user_id"`
	DeviceName string    `json:"device_name"`
	PublicKey  string    `json:"public_key"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	UserID       int32     `json:"user_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Ispremium    bool      `json:"ispremium"`
	CreatedAt    time.Time `json:"created_at"`
}
