name: Deploy to OCI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pastey-api

    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Load secrets from AWS
        run: aws secretsmanager get-secret-value --secret-id pastey --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env
      
      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: pastey
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Build, tag, and push docker image to OCIR
        env:
          REPOSITORY: ${{ steps.get-ocir-repository.outputs.repo_path }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --output type=docker --platform linux/arm64 -t "$REPOSITORY:$IMAGE_TAG" .
          docker push "$REPOSITORY:$IMAGE_TAG"

      - name: Execute python script
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_DNS_RECORD_ID: ${{ secrets.CF_DNS_RECORD_ID }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        run: |
          pip install -r ./scripts/requirements.txt
          python3 scripts/deploy_oci.py ${{ secrets.OCI_COMPARTMENT_OCID }} ${{ secrets.OCI_SUBNET_OCID }} ${{ steps.get-ocir-repository.outputs.repo_path }} ${{ secrets.ADOMAIN }} ${{ github.sha }}